### ISSUE TITLE
KeyError: 'tag_name'

### ISSUE THREAD

**Issue by danny-su** [sublimelsp/LSP-ltex-ls#6]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danny/Library/Application Support/Sublime Text 3/Installed Packages/LSP-ltex-ls.sublime-package/plugin.py", line 103, in <module>
  File "/Users/danny/Library/Application Support/Sublime Text 3/Installed Packages/LSP-ltex-ls.sublime-package/plugin.py", line 98, in fetch_latest_release
KeyError: 'tag_name'
```

`version: 4169 osx arm64 channel: stable`

**Comment by LDAP** [comment]
I'am looking into this this weekend

**Comment by LDAP** [comment]
I pushed a new version. Feel free to reopen if the issue persists.
